SELECT
    D.did,
    PDS.did PARENT_DID,
    PDS.create_at,
    PDS.create_by,
    PDS.modify_at,
    PDS.modify_by
FROM DATASETS D
LEFT OUTER JOIN PARENTS DSP ON DSP.DATASET_ID = D.DATASET_ID
LEFT OUTER JOIN DATASETS PDS ON PDS.DATASET_ID = DSP.PARENT_ID
